server:
  port: 8881

spring:
  application:
    name: leucam-gateway-service
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 15000
  ignored-services: '*'
  routes:
    leucam-order-service:
      path: /leucam-order-service/**
      serviceId: leucam-order-service
      stripPrefix : true
      sensitiveHeaders:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 32000


ribbon:
  ReadTimeout: 15000
  connection-timeout: 15000
  eureka:
    enabled: true